FROM node:18 AS build

WORKDIR /app

COPY project-frontend/package.json project-frontend/package-lock.json ./

RUN npm install

COPY project-frontend/ ./

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]